### ISSUE TITLE
SparseLinearBatch implementation

### ISSUE THREAD

**Issue by davidBelanger** [fstrub95/nnsparse#1]
I was just browsing the web for stuff for sparse data in torch. It looks like this repo is being developed right now, so I totally understand if the stuff I'm reading on github.com isn't in a stable state, isn't fully optimized, etc.

I just want to point out that SparseLinearBatch:accGradParameters() might not being implemented as efficiently as possible. I think the code I pasted below is operationally equivalent, since the SparseLinearAccGradParameters already adds the grad parameters for the current computation, rather than replacing it. You don't need to manage an accumulator outside of the one already provided in self.layer. This avoids unnecessary computation in the inner loop.

function SparseLinearBatch:accGradParameters(input, gradOutput)

   if torch.isTensor(input) then 
      self.layer:accGradParameters(input, gradOutput)

   elseif type(input) == "table" then

```
  -- initialize memory without parasatizing non-batch method
  self.gradWeightBuf = self.gradWeightBuf or torch.zeros(self.layer.gradWeight:size())
  self.gradBiasBuf   = self.gradBiasBuf   or torch.zeros(self.layer.gradBias:size())

  local k = 0
  for _, oneInput in pairs(input) do
     k = k + 1
     self.layer:accGradParameters(oneInput, gradOutput[k])
  end
```

   else
      error('input must be a either a 2D matrices or a table of 2D matrices')
   end

end

**Comment by davidBelanger** [comment]
Also, in updateOutput, I think you need

```
  for _, oneInput in pairs(input) do
     k = k + 1 -- when input is not a contiguous table
     self.outputBuf[k]:copy(self.layer:updateOutput(oneInput))
  end
```

Previously, you had
         self.outputBuf[k] = self.layer:updateOutput(oneInput)

This just sets self.outputBuf[k] to layer.output. This reference stays the same, but its value changes  every time you call updateOutput.

**Comment by fstrub95** [comment]
Hi David, 
You are right about SparseLinearBatch:AccGradParameters, it is better to use the container in the SparseLinear Layer. This remove some unnecessary computations.
Regarding updateOutput, no worries, this is a copy :)
For instance:

th> y  = torch.ones(5, 10)
th> x = torch.zeros(10)
th> y[2] = x 
th> y
 1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
[torch.DoubleTensor of size 5x10]
th> x:fill(2)
 2
[...]
th> y
 1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
[torch.DoubleTensor of size 5x10]

There is no reference because we are working on a sub-dimension of the container. The final storage must remain contiguous (-> no ref). The code is unit-tested and compared with with nn.Linear.  

Thank you for reporting!

**Comment by fstrub95** [comment]
Commit:
https://github.com/fstrub95/nnsparse/commit/f23724f885e0ae6b4e27857dbdceaf6a257448be

**Comment by davidBelanger** [comment]
cool! glad I could help. Thanks for clarifying with updateOutput. That's a
cool way to do it.
